name: Generate GitHub Trophies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: alphacodex143
          file: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Trophy
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub trophies"
          file_pattern: trophy.svg
